# Generated by Django 3.1.4 on 2020-12-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneySum', models.IntegerField(default=0)),
                ('DateOfStart', models.DateTimeField(auto_now_add=True)),
                ('DateOfFinish', models.DateTimeField(blank=True, null=True)),
                ('SpendToday', models.IntegerField(default=0)),
                ('SpendSum', models.IntegerField(default=0)),
                ('RestSum', models.IntegerField(default=0)),
                ('AvaibleSumToday', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='currentbudget',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
